### ISSUE TITLE
[Screen Readers] testing / feedbacks - Help Wanted 👋

### ISSUE THREAD

**Issue by AlaricBaraou** [pmndrs/react-three-a11y#13]
If you're willing to help me test those accessibility features before they're launched **please DM me on Twitter and we'll discuss how you could give me a hand !**
- [`twitter 👋 @AlaricBaraou`](https://twitter.com/AlaricBaraou)

As I don't own a copy of each phone / OS / screen readers etc and since most of accessibility is only testable by humans, I'd love it if some of you could try the different versions / updates before I launch them or simply give me feedbacks about the current ones.

While we use simple semantic HTML to make our canvas accessible, we obviously don't use it in the way it was initially thought.
I may and probably have missed some accessibility issues so far with the current solution and there is a limit to the amount of them a single guy can catch 😅

**Looking forward your feedbacks** 🙌

**Comment by jasonwebb** [comment]
Hi @AlaricBaraou! I was just about to DM you on Twitter, but it looks like you have messaging disabled, or maybe just limited to mutual follows. I'd love to help out! 

A little about me -- I work as a Developer Advocate at an accessibility auditing and consulting company, and I get to work closely with a group of Blind and low-vision experts, who are either native screen reader users or what we call "hybrid" users (people who use a combination of AT).

I've been working with JAWS and NVDA for about 1.5 years now, and have learned a LOT about both WCAG and the UX side of accessibility (what real Blind/low-vision users actually need, expect, and enjoy). I'd be happy to share some observations based on the [demo project](https://n4rzi.csb.app/), just let me know where / how you would prefer them!

**Comment by AlaricBaraou** [comment]
Hello @jasonwebb 
Thank you for reaching out ! I've enabled the DM I had no idea they were disabled.
It sounds like you could bring A LOT of knowledge from your experiences.
I've sent you a DM on Twitter to discuss it more there, thanks again !
