### ISSUE TITLE
Support Accessibility Object Model when it's available

### ISSUE THREAD

**Issue by souporserious** [pmndrs/react-three-a11y#15]
First, just want to say this is such an awesome library! I love that you've been able to augment canvas with React to get proper accessibility. I was curious if you've looked into [AOM](https://wicg.github.io/aom/spec/) at all and do you think it will be viable to move to once it becomes official?

**Comment by AlaricBaraou** [comment]
Thank you 🙂

Right now I don't know much about AOM and the current goal of the library is to provide as many solutions as possible with the currently available options.

I believe a good majority of the current websites using WebGL can be fully accessible with simple transparent semantic HTML.

Then, I'll try to find solutions for the edge cases, and that's probably when solutions like AOM might become handy.

And to answer you about the viability of AOM, I don't think I'm qualified to judge it. In the end, I'll follow the standards.

**Comment by souporserious** [comment]
Yeah, absolutely! Totally understandable. I always wondered if AOM could be polyfilled. Seems plausible to do something similar to what you've done. Anyways, was just curious and thought I'd ask. We can revisit when the spec is further along and actually implemented in a browser 😇
