### ISSUE TITLE
A11y required props

### ISSUE THREAD

**Issue by servinlp** [pmndrs/react-three-a11y#20]
Hi there,

I'm trying to use this package with typescript and it seems that on, for what I've seen at the moment, the `A11y` component only has required props. Is this for a reason? If not, which ones are actually required?

**Comment by AlaricBaraou** [comment]
Hello @servinlp 

I'm not very familiar with typescipt so It's very likely that I marked all property as required by accident.

The only really required prop would be the role one. 
Then depending on the role, other props might be necessary or not usable at all. 

If there is a way to have conditional required field in typescript I'd be happy to update the package so it doesn't ask for props that you don't actually need.

You can see what props are expected for each roles here https://github.com/pmndrs/react-three-a11y#the-three-roles-of-the-a11y-component

If something isn't clear, feel free to join the poimandres discord https://discord.gg/poimandres 
There is a react-three-a11y channel where I'd be happy to help and discuss.

**Comment by servinlp** [comment]
Hi @AlaricBaraou 

After a little searching I came across this, [Discriminated Union](https://basarat.gitbook.io/typescript/type-system/discriminated-unions). Might be something we could use to specify what props are required with what role.

If I have some time I'll play around with it to see if this would work.

**Comment by AlaricBaraou** [comment]
Thank you @servinlp , that would be amazing.

I'm a little busy recently but if I I get a chance I'll also try your suggestion.

Please feel free to reach out if you have any question about react-three-a11y.

**Comment by AlaricBaraou** [comment]
Hello @servinlp 

I'm dealing with this today or tomorrow at the latest.
Since I have time, I don't want you to use your time unnecessary.
I'll still be happy to have feedback from you once I'm done though !

**Comment by AlaricBaraou** [comment]
@servinlp It should work fine now with the latest 2.0.1  

Let me know if this fix your issue when you have time.

**Comment by servinlp** [comment]
Cool, I'll probably will continue with this somewhere this week.

**Comment by AlaricBaraou** [comment]
I'll assume it's working fine since the release and close this issue.

Let me know if anything else seems off ! 🙂
