### ISSUE TITLE
ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by indiejoseph** [pmndrs/react-three-a11y#39]
Got this error after upgraded React 18, probably due to React DOM Portal in three A11y.

reference :https://github.com/chakra-ui/chakra-ui/issues/5795

![Screen Shot 2022-04-08 at 11 50 12 AM](https://user-images.githubusercontent.com/577551/162359149-cc7d11a0-083e-4c53-928b-666463ccd888.png)

**Comment by indiejoseph** [comment]
https://github.com/pmndrs/react-three-a11y/pull/40

**Comment by AlaricBaraou** [comment]
Thank you for reporting, I'll try to take care of this by the end of the week.

**Comment by jooohyunpark** [comment]
What's the status of this? The issue persists at v2.2.4. Thanks in advance.

**Comment by AlaricBaraou** [comment]
@jooohyunpark this is solved in v3.0.0
Thanks everyone for your patience and help.
