### ISSUE TITLE
Add demo link somewhere

### ISSUE THREAD

**Issue by marcofugaro** [pmndrs/react-three-a11y#9]
The demo link https://n4rzi.csb.app/ is really useful to test hands on how the library behaves.

Would be useful for other users if it was added in the link section on the right or just in the readme.

<img src="https://user-images.githubusercontent.com/7217420/104432476-59c69880-5589-11eb-9377-33db44419597.png" width="300"/>

**Comment by drcmda** [comment]
Added it to readme.md
